Sprint 06
flukekoh/MovieQuiz-ios pull request #3
Opened 2022-10-31 15:03 UTC by flukekoh

Сделал изменения по 6 спринту по сетевому взаимодействию

2022-10-31 15:58 UTC, mmbabaev requested changes

2022-10-31 15:58 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +//        questionFactory?.requestNextQuestion()
не нужно оставлять закомментированный код

2022-10-31 15:58 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +//            image: UIImage(named: model.image) ?? UIImage(),
не нужно

2022-10-31 15:58 UTC, mmbabaev commented on MovieQuiz/Services/MoviesLoader.swift
> +                    return
не хватает обработки ошибки, если десериализхация данных не получилаьс

2022-10-31 15:58 UTC, mmbabaev commented on MovieQuiz/Services/MoviesLoader.swift
> +                    return
<img width="743" alt="Screen Shot 2022-10-31 at 18 49 34" src="https://user-images.githubusercontent.com/12600807/199050612-6981f00e-8b06-4d98-8b4a-75f66bf0019a.png">

2022-10-31 15:58 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +        //        let index = (0..<questions.count).randomElement() ?? 0
давайте удалим

2022-10-31 15:58 UTC, mmbabaev commented on MovieQuiz.xcodeproj/project.pbxproj
>  		A24AE76D28F5612B00219BAE /* AlertModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = A24AE76C28F5612B00219BAE /* AlertModel.swift */; };
<img width="459" alt="Screen Shot 2022-10-31 at 18 52 39" src="https://user-images.githubusercontent.com/12600807/199051360-fb9af250-1f1a-4a4f-8c2a-d07898ebafc5.png">
У вас проблема с добавлением шрифтов. Можно проверить, скачав ваш проект с гитхаба

2022-10-31 15:58 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self?.present(alert, animated: true, completion: nil)
При нажатии на кнопку повторить алерт пропадает и ничего не происходит

2022-10-31 16:22 UTC, flukekoh commented on MovieQuiz/Services/MoviesLoader.swift
> +                    return
я могу добавить просто перечисление для ошибки и обработать так?
`if let mostPopularMovies = try? JSONDecoder().decode(MostPopularMovies.self, from: mostPopularMoviesData) {
                    handler(.success(mostPopularMovies))
                } else {
                    handler(.failure(JSONError.unexpectedJSON))
                }`

2022-10-31 16:34 UTC, flukekoh commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self?.present(alert, animated: true, completion: nil)
это вообще не используемая функция. сейчас ее удалю. осталась с первой попытки реализации алерта

2022-11-01 10:00 UTC, mmbabaev commented on MovieQuiz/Services/MoviesLoader.swift
> +                    return
нормально, да

2022-11-01 10:08 UTC, mmbabaev requested changes

2022-11-01 10:08 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +            DispatchQueue.main.async { [weak self] in
В таком варианте self будет захвачен в 62 строке, потому что мы его используем в 63. Нужно на самом верху ослаблять ссылку

2022-11-01 10:08 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self?.present(alert, animated: true, completion: nil)
@flukekoh это не исправлено

2022-11-01 10:08 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self?.present(alert, animated: true, completion: nil)
При нажатии на кнопку повторить алерт пропадает и ничего не происходит

2022-11-01 10:09 UTC, mmbabaev commented
Лучше убрать в сториборде надписи `Label` `Index Label`

2022-11-01 10:55 UTC, flukekoh commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self?.present(alert, animated: true, completion: nil)
@mmbabaev так я же удалил эту функцию

2022-11-01 10:58 UTC, flukekoh commented on MovieQuiz/Services/QuestionFactory.swift
> +            DispatchQueue.main.async { [weak self] in
@mmbabaev это именно тот вариант который приводится у вас в курсе в авторском решении.

2022-11-01 11:00 UTC, flukekoh commented
> 



> 

именно такие имена и верстка в теоретической части курса

2022-11-01 21:30 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self?.present(alert, animated: true, completion: nil)
Прошу прощения, отписал вам не в том месте. Отписался ниже в обработке ошибки (создание AlertModel)

2022-11-01 21:30 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                self.showNextQuestionOrResults()
Это единственное замечание, которое нужно обязательно исправить для принятия работы. 

Вам нужно исправить completion этой AlertModel. Здесь мы должны произвести повторную попытку загрузки данных из сети. Если данные загрузились успешно, запустилась игра. Если данные загрузились с ошибкой, то снова показываем алерт с ошибкой загрузки данных. 

Записал видео что у вас происходит, если нажать "Повторить еще раз".

https://user-images.githubusercontent.com/12600807/199344347-385c2ad1-8128-4e39-8409-63b987339bb0.mp4


Код, который нужно вызвать в completion:
```
guard let self = self else { return }
self.showLoadingIndicator()
self.questionFactory?.loadData()
```

2022-11-01 21:59 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +            DispatchQueue.main.async { [weak self] in
Прошу прощения, я проглядел, что это авторское решение. Обсудили с авторами, авторское решение будет обновлено.

Этот пример вызвал споры и является немного advanced. Важно, что мое замечание в комментарии опциональное и не влияет на решение принять/не принять работу. 

Если интересно, прикладываю playground для объяснения
[WeakSelfClosure copy.playground.zip](https://github.com/flukekoh/MovieQuiz-ios/files/9914168/WeakSelfClosure.copy.playground.zip)

Если closure будет хранится где-то внутри (в playground я добавил хранение в NetworkClient), то создается retain cycle. 
Для захвата [weak self] в внутренней closure происходит неявный захват self во внешней closure. Внешняя closure сильно захватит self. 

Поэтому если мы хотим работать с weak self в "пирамиде" кложур (вложенными друг в друга), то нужно захватывать self слабо во внешней closure.

Пример из playground можно починить, если перенести [weak self] выше

2022-11-02 11:39 UTC, flukekoh commented on MovieQuiz/Services/QuestionFactory.swift
> +            DispatchQueue.main.async { [weak self] in
@mmbabaev спасибо большое за пояснение. То есть если в клоужере я захватываю переменную из объекта то как будто бы происходит захват ссылки которую он видит. и если он видит выше только другой клоужер то ссылка будет сильная так как иерархически он это не пробросит. так? извиняюсь что так криво своими словами

2022-11-03 04:33 UTC, merged